# Generated by Django 5.1.1 on 2024-09-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0003_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='tier',
            new_name='subscription_type',
        ),
    ]
