# Generated by Django 5.1.1 on 2024-09-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0004_rename_tier_subscription_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boipoka_app.book')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boipoka_app.subscription')),
            ],
        ),
    ]
