# Generated by Django 5.1.1 on 2024-10-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0008_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='reissue_state',
            field=models.BooleanField(default=False),
        ),
    ]
