# Generated by Django 5.1.1 on 2024-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0011_rename_is_read_borrowing_marked_as_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='is_damagedorlost',
            field=models.BooleanField(default=False),
        ),
    ]
