# Generated by Django 5.1.1 on 2024-10-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0012_borrowing_is_damagedorlost'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
