# Generated by Django 5.1.1 on 2024-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0013_borrowing_fine_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
