# Generated by Django 5.1.1 on 2024-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0014_book_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='fine_paid_approved',
            field=models.BooleanField(default=False),
        ),
    ]
