# Generated by Django 5.1.1 on 2024-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0017_borrowing_damagedlostat_borrowing_fine_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returnedDash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
