# Generated by Django 5.1.1 on 2024-10-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0018_borrowing_returneddash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='returnedDash',
        ),
    ]
