# Generated by Django 5.1.1 on 2024-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0019_remove_borrowing_returneddash'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='returnedDash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
