# Generated by Django 5.1.1 on 2024-10-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0022_remove_book_is_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='marked_as_unread',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='returnedDash',
        ),
    ]
