# Generated by Django 5.1.1 on 2024-10-13 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipoka_app', '0023_remove_subscription_marked_as_unread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedorLostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_paid', models.BooleanField(default=False)),
                ('fine_paid_approved', models.BooleanField(default=False)),
                ('fine_paid_at', models.DateTimeField(blank=True, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boipoka_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
